version: '3.8'

services:
  # React.js service
  react-app:
    build:
      context: ./frontend  # Path to your React app
    ports:
      - "5173:80"
    depends_on:
      - spring-boot-app
    networks:
      - app-network

  # Spring Boot service
  spring-boot-app:
    build:
      context: ./backend/studentManagementSystemBackend/studentManagementSystemBackend   # Path to your Spring Boot app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres-db
    networks:
      - app-network

  # PostgreSQL service
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

# Define a custom network to allow communication between containers
networks:
  app-network:
    driver: bridge

# Define volumes for persistent PostgreSQL data
volumes:
  postgres-data:
